config/routes.rb
Rails.application.routes.draw do
  resources :slideshows do
    get :carousel, on: :member
    resources :entries, only: [:index]
  end

  resources :categories

  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  get '/auth/:provider/disable', to: 'users#disable_provider'
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  resources :sessions
  resources :memberships

  resources :users

  resources :feeds do
    get :more_info
    
    resources :entries, only: [:new, :index, :create, :show], constraints: { id: /.*/ } do
    end
    
    resources :slideshows, only: [:add, :remove] do
      member do
        get :add
        get :remove
      end
    end
  end
  
  resources :entries, only:[:show,:update,:edit] do
    resource :highlights
  end
  
  get '/preview/*id(.:format)' => DragonflyCache.endpoint(Dragonfly.app) { |params, app|
    image = Entry.where('preview_uid LIKE ?', "#{params[:id]}%").first.preview
    format = params[:format] || 'jpg'
    size = params[:size] || '500x500'

    begin
      unless image.image?
        image = app.fetch_file(Rails.root.join("app/assets/images/missing.jpg"))
      end
    rescue
      image = app.fetch_file(Rails.root.join("app/assets/images/missing.jpg"))
    end

    image = image.encode(format) if image.format.to_s != format
    image = image.thumb(size)
    image
  }, as: :entry_preview

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'feeds#index'
end

app/models/slideshow.rb
class Slideshow < ActiveRecord::Base
  has_many :slideshow_feeds
  has_many :feeds, through: :slideshow_feeds
  has_many :entries, ->(owner) {
    if owner.highlights_only?
      return self.highlighted 
    end
    return self
  }, through: :feeds
  
  validates :title, presence: true
  validates :uid, uniqueness: true
  
  before_create :set_unique_uid
  
  accepts_nested_attributes_for :slideshow_feeds
  accepts_nested_attributes_for :feeds
  
  
  def preview_entry
    self.entries.recent.first
  end
  
  def self.generate_uid
    SecureRandom.hex(3)
  end
  
  def set_unique_uid
    while(self.uid.nil? or Slideshow.where(uid: self.uid).count > 0) do
      self.uid = Slideshow.generate_uid
    end
  end
  
  def to_param
    self.uid
  end
  
  def to_s
    self.title
  end
end

app/controllers/slideshows_controller.rb
class SlideshowsController < ApplicationController
  before_action :set_slideshow, only: [:show, :edit, :update, :destroy, :add, :remove, :carousel]
  before_action :set_device_type

  load_and_authorize_resource

  # GET /slideshows
  # GET /slideshows.json
  def index
    @slideshows = Slideshow.order(title: :asc)
  end

  def add
    @feed = Feed.friendly.find(params[:feed_id])
    @slideshow.feeds << @feed unless @slideshow.feeds.include?(@feed)

    msg = "Added #{@feed} to slideshow"
    respond_to do |format|
      format.html {
        flash[:notice] = msg
        redirect_to @slideshow
      }
      format.js {
        flash.now[:notice] = msg
        redirect_via_turbolinks_to @slideshow
      }
    end
  end

  def remove
    @feed = Feed.friendly.find(params[:feed_id])
    @slideshow.feeds.destroy(@feed)
    msg = "Removed #{@feed} from slideshow"
    respond_to do |format|
      format.html {
        flash[:notice] = msg
        redirect_to @slideshow
      }
      format.js {
        flash.now[:notice] = msg
        redirect_via_turbolinks_to @slideshow
      }
    end
  end

  def carousel
    @entries = @slideshow.entries.recent.limit(12)

    respond_to do |format|
      format.html
      format.html.phone {
        render layout: 'mobile'
      }
    end
  end

  # GET /slideshows/1
  # GET /slideshows/1.json
  def show
    @entries = @slideshow.entries.recent.limit(12)

    @active_feeds = @slideshow.feeds.order(title: :asc)
    @available_feeds = Feed.where.not(id: @slideshow.feed_ids).order(title: :asc)
  end

  # GET /slideshows/new
  def new
    @slideshow = Slideshow.new
  end

  # GET /slideshows/1/edit
  def edit
  end

  # POST /slideshows
  # POST /slideshows.json
  def create
    @slideshow = Slideshow.new(slideshow_params)

    respond_to do |format|
      if @slideshow.save
        format.html { redirect_to @slideshow, notice: 'Slideshow was successfully created.' }
        format.json { render :show, status: :created, location: @slideshow }
      else
        format.html { render :new }
        format.json { render json: @slideshow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slideshows/1
  # PATCH/PUT /slideshows/1.json
  def update
    respond_to do |format|
      if @slideshow.update(slideshow_params)
        format.html { redirect_to @slideshow, notice: 'Slideshow was successfully updated.' }
        format.json { render :show, status: :ok, location: @slideshow }
      else
        format.html { render :edit }
        format.json { render json: @slideshow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slideshows/1
  # DELETE /slideshows/1.json
  def destroy
    @slideshow.destroy
    respond_to do |format|
      format.html { redirect_to slideshows_url, notice: 'Slideshow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected

    # Use callbacks to share common setup or constraints between actions.
    def set_slideshow
      @slideshow = Slideshow.find_by_uid(params[:id].downcase)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slideshow_params
      params.require(:slideshow).permit(:title, :highlights_only)
    end
end

app/helpers/slideshows_helper.rb
module SlideshowsHelper
end

app/views/slideshows/_carousel.html.haml
- variant_class ||= 'desktop'
- unless entries.empty?
  #slideshow-carousel.carousel.slide{ data: { pause: 'false', interval: 10000, wrap: false }, class: variant_class }
    %ol.carousel-indicators
      - entries.count.times do |i|
        %li{ class: (i==0 ? 'active' : ''), data: { target: '#slideshow-carousel', slide_to: i } }
    .carousel-inner
      - entries.each do |entry|
        .item{ class: (entries.first == entry ? 'active' : '') }
          - thumb = entry.image.thumb('1280x800>')
          = image_tag thumb.url, alt: entry.event_at
          .carousel-caption
            %h3
              = entry.feed.title
              - if entry.highlight.present?
                %i.fa.fa-star.highlight{ title: entry.highlight.description, data: { behavior: 'tooltip' } }
                
            %p
              = link_to entry do
                = entry.event_at
                = "(#{time_ago_in_words(entry.event_at)} ago)"
    %a.left.carousel-control{ class: (variant_class != 'desktop' ? 'hidden' : ''), href: '#slideshow-carousel', role: "button", data: { slide: "prev" } }
      %span.glyphicon.glyphicon-chevron-left
    %a.right.carousel-control{ class: (variant_class != 'desktop' ? 'hidden' : ''), href: '#slideshow-carousel', role: "button", data: { slide: "next" } }
      %span.glyphicon.glyphicon-chevron-right
  :javascript
    $(document).ready(function() {
      $("#slideshow-carousel").carousel();
    });
    $(document).on('slide.bs.carousel', function(e) {
      if (e.direction != 'left') {
        // don't do anything when sliding back
        return;
      }
      if ($(this).find('.item:last').hasClass('active')) {
      
        Turbolinks.visit(location.path);
      }
    });
    $(document).one('page:fetch', function() {
      // disable previous slideshow instance
      $(document).off('slide.bs.carousel');
      $("#slideshow-carousel").remove();
    })

app/views/slideshows/_form.html.haml
= bootstrap_nested_form_for(@slideshow) do |f|
  = f.alert_message "Please fix the errors below."
  = f.text_field :title
  = f.check_box :highlights_only
  
  .form-group.pull-right
    = link_to slideshows_path, class: 'btn btn-default' do
      Cancel
    = f.primary

app/views/slideshows/carousel.html+phone.haml
= render 'carousel', entries: @entries, variant_class: 'mobile'

app/views/slideshows/carousel.html.haml
= render 'carousel', entries: @entries

app/views/slideshows/edit.html.haml
%h1 Editing slideshow
= render 'form'

app/views/slideshows/index.html.haml
%h1 
  Listing slideshows
  = link_to new_slideshow_path, class: 'btn btn-success pull-right' do
    %i.fa.fa-plus
    New Slideshow
- @slideshows.each do |slideshow|
  = link_to slideshow, class: 'thumbnail pull-left' do
    %h4.text-center= slideshow
    = image_tag slideshow.entries.recent.first.image.thumb('200x200#').url if slideshow.entries.recent.any?
    %h1.text-center
      = slideshow.uid.upcase

app/views/slideshows/new.html.haml
%h1 New slideshow
= render 'form'

app/views/slideshows/show.html.haml
.row
  .col-lg-8.col-md-8.col-sm-8
    %h1
      = @slideshow
      slideshow
    .lead
      %p
        Your slideshow code is:
        %div.text-center
          %b.text-info{ style: 'font-size: 3em;' }= @slideshow.uid.upcase
      %p
        Enter the above code into the
        %b Puffin Feeder Slideshow
        application to access the imagery feeds


    %h3 Slideshow Preview
    = render 'carousel', entries: @entries

  .col-lg-4.col-md-4.col-sm-4
    .panel.panel-default
      .panel-heading
        .panel-title Information
      .panel-body
        %dl.dl-horizontal
          %dt Only shows highlights?
          %dd= @slideshow.highlights_only? ? 'Yes' : 'No'

        .row
          .col-lg-6.col-md-6.col-sm-6
            = link_to carousel_slideshow_path(@slideshow), class: 'btn btn-primary btn-block' do
              %i.fa.fa-eye
              View
          .col-lg-6.col-md-6.col-sm-6
            = link_to edit_slideshow_path(@slideshow), class: 'btn btn-default btn-block' do
              %i.fa.fa-gears
              Change Settings
      %ul.list-group
        %li.list-group-item Feeds:
        - @active_feeds.each do |feed|
          - next if feed.entries.available.empty?
          %li.list-group-item.clearfix
            .pull-left
              = link_to [feed, :entries], target: :_blank do
                = image_tag feed.preview_entry.image.thumb('50x50#').url, style: 'margin-right: 10px;'
            %b= link_to feed, [feed,:entries], target: :_blank
            - if can? :manage, @slideshow
              %br/
              = link_to [:remove, feed, @slideshow], remote: true, class: 'btn btn-danger' do
                Remove from slideshow
        - if can? :manage, @slideshow
          - @available_feeds.each do |feed|
            - next if feed.class == HighlightFeed or feed.preview_entry.nil?
            %li.list-group-item.clearfix
              .pull-left
                = link_to [feed, :entries], target: :_blank do
                  = image_tag feed.preview_entry.image.thumb('50x50#').url, style: 'margin-right: 10px;'
              %b= link_to feed, [feed, :entries], target: :_blank
              %br/
              = link_to [:add, feed, @slideshow], remote: true, class: 'btn btn-success' do
                Add to slideshow