config/routes.rb
Rails.application.routes.draw do
  resources :slideshows do
    get :carousel, on: :member
    resources :entries, only: [:index]
  end

  resources :categories

  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  get '/auth/:provider/disable', to: 'users#disable_provider'
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  resources :sessions
  resources :memberships

  resources :users

  resources :feeds do
    get :more_info
    
    resources :entries, only: [:new, :index, :create, :show], constraints: { id: /.*/ } do
    end
    
    resources :slideshows, only: [:add, :remove] do
      member do
        get :add
        get :remove
      end
    end
  end
  
  resources :entries, only:[:show,:update,:edit] do
    resource :highlights
  end
  
  get '/preview/*id(.:format)' => DragonflyCache.endpoint(Dragonfly.app) { |params, app|
    image = Entry.where('preview_uid LIKE ?', "#{params[:id]}%").first.preview
    format = params[:format] || 'jpg'
    size = params[:size] || '500x500'

    begin
      unless image.image?
        image = app.fetch_file(Rails.root.join("app/assets/images/missing.jpg"))
      end
    rescue
      image = app.fetch_file(Rails.root.join("app/assets/images/missing.jpg"))
    end

    image = image.encode(format) if image.format.to_s != format
    image = image.thumb(size)
    image
  }, as: :entry_preview

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'feeds#index'
end

app/models/highlight.rb
class Highlight < ActiveRecord::Base
  belongs_to :user
  has_one :entry
  
  validates :description, presence: true, length: { in: 6..140 }
  
  def to_s
    self.description
  end
end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
  before_action :set_entry
  before_action :set_highlight, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /highlights
  # GET /highlights.json
  def index
    @highlights = Highlight.all
  end

  # GET /highlights/1
  # GET /highlights/1.json
  def show
  end

  # GET /highlights/new
  def new
    @highlight = Highlight.new
  end

  # GET /highlights/1/edit
  def edit
  end

  # POST /highlights
  # POST /highlights.json
  def create
    @highlight = @entry.build_highlight(highlight_params)
    @highlight.user = current_user
    
    respond_to do |format|
      if @highlight.save
        format.html { redirect_to @entry, notice: 'Highlight was successfully created.' }
        format.json { render :show, status: :created, location: @highlight }
      else
        format.html { render :new }
        format.json { render json: @highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /highlights/1
  # PATCH/PUT /highlights/1.json
  def update
    respond_to do |format|
      if @highlight.update(highlight_params)
        format.html { redirect_to @entry, notice: 'Highlight was successfully updated.' }
        format.json { render :show, status: :ok, location: @highlight }
      else
        format.html { render :edit }
        format.json { render json: @highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /highlights/1
  # DELETE /highlights/1.json
  def destroy
    @highlight.destroy
    respond_to do |format|
      format.html { redirect_to @entry, notice: 'Highlight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:entry_id]) if params[:entry_id].present?
    end
    
    def set_highlight
      @highlight = @entry.highlight unless @entry.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def highlight_params
      params.require(:highlight).permit(:user_id, :description)
    end
end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/views/highlights/_form.html.haml
= bootstrap_form_for(@highlight, url: entry_highlights_path(@entry)) do |f|
  = f.alert_message "Please fix the errors below."
  = f.text_area :description, rows: 2
  .pull-right.form-group
    = link_to @entry, class: 'btn btn-default' do
      Cancel
    = f.primary

app/views/highlights/edit.html.haml
%h1 Editing highlight
= render 'form'

app/views/highlights/index.html.haml
%h1 Listing highlights
%table
  %thead
    %tr
      %th User
      %th Description
      %th{:colspan => "3"}
  %tbody
    - @highlights.each do |highlight|
      %tr
        %td= highlight.user_id
        %td= highlight.description
        %td= link_to 'Show', highlight
        %td= link_to 'Edit', edit_highlight_path(highlight)
        %td= link_to 'Destroy', highlight, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Highlight', new_highlight_path

app/views/highlights/new.html.haml
%h1 New highlight
= render 'form'

app/views/highlights/show.html.haml
%p
  %strong User:
  = @highlight.user
%p
  %strong Description:
  = @highlight.description