config/routes.rb
Rails.application.routes.draw do
  resources :slideshows do
    get :carousel, on: :member
    resources :entries, only: [:index]
  end

  resources :categories

  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  get '/auth/:provider/disable', to: 'users#disable_provider'
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  resources :sessions
  resources :memberships

  resources :users

  resources :feeds do
    get :more_info
    
    resources :entries, only: [:new, :index, :create, :show], constraints: { id: /.*/ } do
    end
    
    resources :slideshows, only: [:add, :remove] do
      member do
        get :add
        get :remove
      end
    end
  end
  
  resources :entries, only:[:show,:update,:edit] do
    resource :highlights
  end
  
  get '/preview/*id(.:format)' => DragonflyCache.endpoint(Dragonfly.app) { |params, app|
    image = Entry.where('preview_uid LIKE ?', "#{params[:id]}%").first.preview
    format = params[:format] || 'jpg'
    size = params[:size] || '500x500'

    begin
      unless image.image?
        image = app.fetch_file(Rails.root.join("app/assets/images/missing.jpg"))
      end
    rescue
      image = app.fetch_file(Rails.root.join("app/assets/images/missing.jpg"))
    end

    image = image.encode(format) if image.format.to_s != format
    image = image.thumb(size)
    image
  }, as: :entry_preview

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'feeds#index'
end

app/views/layouts/_flash_messages.html.haml
- flash.each do |type,msg|
  .alert{ class: "alert-#{bootstrap_flash_type(type)}" }
    %button.close{ data: { dismiss: 'alert' }} &times;
    = msg

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-gina.navbar-static-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle{ type: 'button', data: { toggle: 'collapse', target: '#header-navbar' }}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_url, class: 'navbar-brand' do
        = image_tag 'ic_launcher.png'
        %span.gina GINA
        Puffin Feeder
    #header-navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if signed_in?
          %li
            = link_to feeds_path do
              Feeds
          %li
            = link_to slideshows_path do
              Slideshows
          %li
            = link_to logout_path do
              Logout
        - else
          %li
            = link_to login_path do
              Login

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FeederWeb
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %meta{ name: 'viewport', content: 'width=device-width' }
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container-fluid
      = render 'layouts/flash_messages'
      = yield

app/views/layouts/mobile.html.haml
!!!
%html
  %head
    %title FeederWeb
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{ name: 'apple-mobile-web-app-capable', content: 'yes' }
    %meta{ name: 'mobile-web-app-capable', content: 'yes' }
    %meta{ name: 'viewport', content: 'width=device-width' }
  %body
    :css
      body { background: #000; }
      img { max-width: 100%; }
    = yield
    :javascript
      window.scrollTo(0,1);